### ISSUE TITLE
missing $sth->finish

### ISSUE THREAD

**Issue by harry-bix** [jhthorsen/mojo-mysql#2]
Mojo::mysql::Database::_enqueue should call $sth->finish
This is mandatory if mysql_use_result option is used

eval { $sth->finish if $sth->{Active}; };

**Comment by jhthorsen** [comment]
I need more information. Example code which fail or misbehave. Also, why would you need to put eval{} around the code? It doesn't make the code very robust.

**Comment by harry-bix** [comment]
You can just append ?mysql_use_result=1 in TEST_ONLINE connection string. Unit tests will fail.

**Comment by harry-bix** [comment]
When mysql_use_result is used and you need to interrupt transfer is to kill the connection from server side using another connection. Then finish of the killed connection will raise unnecessary error:
(in cleanup) DBD::mysql::st finish failed: Lost connection to MySQL server during query at lib/Mojo/mysql/Database.pm line 71.
That's why I used eval.

**Comment by jhthorsen** [comment]
I'm not going to add any such code without tests. I simply don't understand the feature good enough to make this work on my own.

**Comment by jhthorsen** [comment]
I might be able to figure this out myself, if you provide me some good examples and proper documentation. I looked at https://metacpan.org/pod/DBD::mysql#mysql_use_result but was not able to see where they mention `finish()`.

**Comment by harry-bix** [comment]
The problem is described here:
http://dev.mysql.com/doc/refman/5.6/en/commands-out-of-sync.html
In DBD::mysql $sth->finish calls mysql_free_result()

**Comment by harry-bix** [comment]
In DBD::mysql $sth->finish frees internal data structures associated with current result. When mysql_store_result is used (default behaviour) this data is cleaned up on next prepare, do, finish or DESTROY call on same handle. With mysql_use_result finish have to be called explicitly.
In both cases internal data will be kept in memory without need between _enqueue and next _dequeue.

dbd_st_finish in https://github.com/CaptTofu/DBD-mysql/blob/master/dbdimp.c

**Comment by jhthorsen** [comment]
Then I don't understand why it should be called in _enqueue. Looks to me as if you need to do it manually after you have retrieved the results. Something like this:

```
sub {
  my ($delay, $err, $res) = @_;
  my $data = $res->hash;
  $res->sth->finish;
  # do stuff...
}
```

I think the eval {} thing will make things a lot harder to debug when it goes wrong. One thing that I might think is a good idea to do something like this:

```
$sth->finish if $sth->{Active} and $options->{mysql_use_result};
```

I'm still not sure. Provide tests and code, and I'm much more likely to accept a pull request.

**Comment by harry-bix** [comment]
finish is not harmful regardless if mysql_use_result or mysql_store_result is used.
eval {} is not needed.
With mysql_use_result Mojo::mysql::Results::rows will always return 0. This is normal behaviour.

I will make some more experiments and then pull request with test code.

**Comment by jhthorsen** [comment]
@harry-bix: Thanks a lot! I really appreciate it :+1:

**Comment by jhthorsen** [comment]
Does this change have any similarities to kraih/mojo-pg@4ce74d17d4624cdda545c4c85f0b98ac77ed7ff8 ?

**Comment by harry-bix** [comment]
No, this is entirely postgresql specific.

**Comment by jhthorsen** [comment]
My question was not very specific... let me try to rephrase: The commit message from mojo-pg contains "_Improved performance for many different queries significantly_". Does `mysql_use_result` improve speed? I've tried to understand what it does from reading up on https://metacpan.org/pod/DBD::mysql#mysql_use_result, but I don't understand why you would not want to use this feature. When does it block..? Is there anything else that is bad with it..?

**Comment by harry-bix** [comment]
mysql_store_result caches the whole resultset on server before starting to stream it to client.
mysql_use_result starts streaming resultset immediately. The problem with mysql_use_result blocking is actually locking. MySQL holds read lock on MYISAM tables in query until the result is transferred. That's why the default behaviour is mysql_store_result. This locking problem does not exists for INNODB since it uses MVCC and reads never lock.

There is visible performance improvement when using mysql_use_result for large resultsets. (I use it for download CSV data in chunked transfer).

**Comment by harry-bix** [comment]
I was working on a different approach but disabling statement cache as done in Mojo::Pg also solves this. #6

**Comment by jhthorsen** [comment]
What is the status of this issue now @harry-bix? Should we close it, because pull requests are replacing this issue?

**Comment by harry-bix** [comment]
This should be closed.
#6 solved problem with **mysql_use_result**
