### ISSUE TITLE
Please include recent Mojo::Pg::Migrations sanity check

### ISSUE THREAD

**Issue by jberger** [jhthorsen/mojo-mysql#21]
Mojo::Pg has added some sanity checking before migrating. The bug that is fixed caused serious production problems when one host had an outdated schema file. The fix in Pg was [this commit](https://github.com/kraih/mojo-pg/commit/92bc312e725042b748950b9c61319d0256d0004a). Can you please port this commit in (and perhaps check for any other outdated changes from upstream).

**Comment by jhthorsen** [comment]
@harry-bix: Are you doing anything with this? I can do it, unless you already have...

**Comment by jhthorsen** [comment]
I'm taking this.

**Comment by jhthorsen** [comment]
@jberger: Part of Mojo::mysql 0.13. Sorry for the long wait.
