### ISSUE TITLE
Failing JSON test on MariaDB 10.3

### ISSUE THREAD

**Issue by Tekki** [jhthorsen/mojo-mysql#41]
If I run t/json.t against MariaDB 10.3 using DBD::mysql 4.049, a single test fails:
```
#   Failed test 'expand json'
#   at t/json.t line 19.
#     Structures begin differing at:
#          $got->{j} = '{"foo":42}'
#     $expected->{j} = HASH(0x7fffc7e9c728)
# Looks like you failed 1 test of 5.
```
When I change `->expand` to `->expand(1)` all tests pass. Is this an incompatibility with MySQL?

Addition: On MySQL 5.7 both `->expand` and `->expand(1)` succeed.

**Comment by jhthorsen** [comment]
I don’t know. Maybe you can check what type MariaDB reports the column has?

https://github.com/jhthorsen/mojo-mysql/blob/master/lib/Mojo/mysql/Results.pm#L66

expand(1) is just guesswork, it doesn’t really care about if the database supports JSON or not.

**Comment by Tekki** [comment]
Type is 252. With
```
my @idx = grep { $types->[$_] == 245 || $types->[$_] == 252 } 0 .. $#$types;
```
all tests pass on MariaDB 10.3, 10.4 and MySQL 5.7.

(Took me some time to get a working test environment; the containers on Dockerhub still run on Latin1.)
