### ISSUE TITLE
Pubsub tests fail on some MySQL versions

### ISSUE THREAD

**Issue by Tekki** [jhthorsen/mojo-mysql#43]
On some versions the pubsub tests fail with the following error:

> t/pubsub.t ................. 1/? DBD::mysql::st execute failed: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable) at [...]mojo-mysql/lib/Mojo/mysql/Migrations.pm line 125.

This error occurs on MySQL 5.7 from Amazon AWS (reported by @ViktorNacht) and on 8.0 from Dockerhub. While I don't know the details of the AWS config, the one on Docker is [quite simple](https://github.com/docker-library/mysql/blob/master/8.0/config/conf.d/docker.cnf).

**Comment by jhthorsen** [comment]
A quick google search tells me that the reason is that the database you’re testing on does not allow the pubsub functions to be created.

I don’t see how I can fix this on my side, so I’m going to close this issue unless further information is submitted.

**Comment by jhthorsen** [comment]
My only suggestion would be to skip the pubsub test if the database does not support the required functions or by an environment variable. But I don’t know what you really want: Do you want the test to be skipped or do you want the code to be fixed?

I also don’t see how the MySQL version is relevant. I’m pretty sure it’s the configuration of the server.

**Comment by Tekki** [comment]
For me it's okay if the tests are skipped. I can prepare a PR.
The error is with 'create trigger' and I think the message is not very helpful. I run 5.6, 5.7 and 8.0 with identical configuration and the tests only fail on 8.0.

**Comment by jhthorsen** [comment]
I would like if it was skipped with an environment variable, like SKIP_PUBSUB_TEST, but the module is also experimental so it could be skipped automatically I guess...

**Comment by Tekki** [comment]
PR is #44.
The error starts with MySQL 8.0.3, changelog for this version is [here](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-3.html).

**Comment by jhthorsen** [comment]
Resolved by #44.

Thanks 👍
