### ISSUE TITLE
SQL::Abstract::mysql join does not match documentation

### ISSUE THREAD

**Issue by daleif** [jhthorsen/mojo-mysql#54]
I'm playing with the `join` examples from the SQL::Abstract::mysql` POD

For example

    my $mysql = Mojo::mysql->new;
    my $abstract = $mysql->abstract;
    # "select * from foo left join bar on (bar.foo_id = foo.id)"
    say $abstract->select(['foo', [-left => 'bar', foo_id => 'id']]);

just gives

    SELECT * FROM `foo`, `ARRAY(0x1c53010)`

Am I missing something really obvious here?

I've tested some of the other nested array ref examples, neither seem to work. Also, not that it does not seem that `t/sql.t` tests any nested array ref examples.

**Comment by jhthorsen** [comment]
I don’t think I will find time to look at this until later this week, but maybe @Tekki knows?

**Comment by Tekki** [comment]
I'm the one who knows nothing, but it seems I forgot to steal a part of the code from Mojo::Pg. I'll take a look at it (@jhthorsen could care about DBD::MariaDB in the meantime).

**Comment by Tekki** [comment]
Made some additions to the module in #56. Thanks to @daleif for reporting this issue.

**Comment by jhthorsen** [comment]
This should be fixed by @Tekki. Hopefully I’ll be able to make a new release later today.
