### ISSUE TITLE
Abstract USING keyword in JOIN syntax

### ISSUE THREAD

**Issue by ViktorNacht** [jhthorsen/mojo-mysql#59]
I'm one of those weird people that adds the singular table name to the id column (e.g. foo_id), which is especially nice for simplifying JOINS:

`SELECT * FROM foo, bar USING (foo_id)`

This seems verbose:

`$db->select(['foo', ['bar', 'foo.foo_id' => 'bar.foo_id' ]);`

(which is what I'm using in my current app)

For the sake of maximum flexibility and completeness, I just wanted to wishlist the option of doing something like this:

```
$db->select(['foo', ['bar', 'foo_id']);
$db->select(['foo', ['bar', [qw(foo_id foo_col2 foo_col3)]]);
```

Just a suggestion. Feel to close this.

**Comment by jhthorsen** [comment]
How can you tell the difference between a table ad column name?

**Comment by Tekki** [comment]
The correct query seems to be
```
SELECT * FROM foo JOIN bar USING (foo_id)
```
For the sake of completeness we could implement the `NATURAL JOIN` too in something like
```
$db->select(['foo', [-natural => 'bar']]);
```
The question is always, where does it make more sense to write a query directly with `$db->query()`? If we implement everything that is imaginable we end up with a module that is unusable. Remember HTML generation with CGI?
By the way, I'd prefer to see `-natural` supported, as the syntax would be consistent with what we already use for left and right joins.

**Comment by jhthorsen** [comment]
@Tekki: Feel free to implement or request a PR 😄

**Comment by ViktorNacht** [comment]
> For the sake of completeness we could implement the `NATURAL JOIN` too in something like
> 
> ```
> $db->select(['foo', [-natural => 'bar']]);
> ```
> By the way, I'd prefer to see `-natural` supported, as the syntax would be consistent with what we already use for left and right joins.

This clearly makes way more sense given the current structure and is very clear and succinct.

My argument against falling back on `$db->query()` is it becomes difficult if not impossible to build SQL across multiple helpers and/or using dynamic controllers, etc. I know that's stating the obvious, but I think this module is wonderful alternative to DBIC.

**Comment by Tekki** [comment]
I could imagine something like that:
```
# -natural
# "select * from foo natural join bar"
$abstract->select(['foo', [-natural => 'bar']]);

# using
# "select * from foo join bar using (foo_id)"
$abstract->select(['foo', [bar => 'foo_id']]);
```

**Comment by Tekki** [comment]
> I could imagine something like that:
> 
> ```
> # -natural
> # "select * from foo natural join bar"
> $abstract->select(['foo', [-natural => 'bar']]);
> 
> # using
> # "select * from foo join bar using (foo_id)"
> $abstract->select(['foo', [bar => 'foo_id']]);
> ```

@ViktorNacht any feedback on this?

**Comment by ViktorNacht** [comment]
I think it's perfect. And I think this module is becoming way better than Mojo::pg.
