### ISSUE TITLE
Feature Request: Add support for SQL::Abstract::Plugin::InsertMulti

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/mojo-mysql#64]
This may not make sense for [Mojo::mysql::Database](https://metacpan.org/pod/Mojo::mysql::Database), but I would be curious to get your thoughts. I think it would be very useful to have the methods in [SQL::Abstract::Plugin::InsertMulti](https://metacpan.org/pod/SQL::Abstract::Plugin::InsertMulti) in Mojo::mysql::Database, along with the corresponding `_p` versions. If it doesn't make sense, I was thinking that this functionality could be added with a role, but that could be strange when reusing Mojo::mysql::Database?

**Comment by jhthorsen** [comment]
I’m not too keen on adding this functionality, but instead of adding a role, you can make a subclass and set `$mysql->database_class`.

**Comment by srchulo** [comment]
That's helpful, thanks! Would you mind telling me why you're against adding this functionality?

**Comment by jhthorsen** [comment]
Because I question usefulness v.s development+maintenance time.

**Comment by srchulo** [comment]
Ah, I see. I use both insert_multi and update_multi frequently, and then find myself doing a loop instead with Mojo::mysql. However, I may not be representative of most users.

I would say feel free to close this, but I see that you added the enhancement and help wanted tags. If I authored a pull request, would you consider adding it? Or should we just close this and I could create a Database object like you mentioned above.

**Comment by jhthorsen** [comment]
A PR is not enough unfortunately. I need someone upvoting or commenting on this issue to consider it.

So “enhancement” was added because I think this is an enhancement, even though I disagree of the degree of usefulness, and then I added “help wanted”, because I would like some help to be convinced I guess... In hindsight I understand my use of tags is confusing. Sorry about that.

**Comment by Tekki** [comment]
> Because I question usefulness v.s development+maintenance time.

When I look at the source code of SQL::Abstract::Plugin::InsertMulti it reminds me of how difficult it is to extend SQL::Abstract. At first sight you think that you can extend it everywhere but then it turns out that you disable big parts of the original code, have to copy it to your own subs, and so on.
It would not be enough to add `insert_multi` to Database, we would have to add it to SQL::Abstract::mysql too if we don't want to lose its extended functionality.

**Comment by srchulo** [comment]
@Tekki, could you point out which parts of SQL::Abstract::Plugin::InsertMulti extends SQL::Abstract? It looks like to me it just uses [-into in Sub::Exporter](https://metacpan.org/pod/Sub::Exporter) to install its methods into the SQL::Abstract namespace, and it's not clear to me how this would cause extended functionality in SQL::Abstract::mysql to be lost. 

To me, it seems like only these lines would need to be added to Mojo::mysql::Database:

```
use SQL::Abstract::Plugin::InsertMulti;
```

And then adding `insert_multi` and `update_multi` to this `monkey_patch` for loop:

```
for my $name (qw(delete insert select update insert_multi update_multi)) {
  # monkey patching
  ...
}
```

Or if we didn't want this functionality in Mojo::mysql::Database itself, add it into a subclass that could be set as the `database_class` in Mojo::mysql:

```
package Mojo::mysql::Database::InsertMulti;
use Mojo::Base 'Mojo::mysql::Database';
use Mojo::Util ();
use SQL::Abstract::Plugin::InsertMulti;

for my $name (qw(insert_multi update_multi)) {
  Mojo::Util::monkey_patch __PACKAGE__, $name, sub {
    my $self = shift;
    my @cb   = ref $_[-1] eq 'CODE' ? pop : ();
    return $self->query($self->mysql->abstract->$name(@_), @cb);
  };
  Mojo::Util::monkey_patch __PACKAGE__, "${name}_p", sub {
    my $self = shift;
    return $self->query_p($self->mysql->abstract->$name(@_));
  };
}

```
Or am I missing something here?

**Comment by Tekki** [comment]
> @Tekki, could you point out which parts of SQL::Abstract::Plugin::InsertMulti extends SQL::Abstract?

InsertMulti has its own internal methods and its own `SWITCH_refkind` blocks. It's not aware of anything happening around it. In SQL::Abstract::mysql we support `INSERT ... ON DUPLICATE KEY` and other MySQL variants of the `INSERT` command. They will not be available if you just add calls to InsertMulti, you would have to duplicate the behavior of `SQL::Abstract::mysql::insert` in your own subclass.
You don't follow this repo so you probably don't know that I'm preparing some extended JSON support (see the temporarily closed PR #51). Even if you make the first change it would be very time consuming to keep `insert` and `insert_multi` in sync.

**Comment by srchulo** [comment]
Ah, I see. Thanks for explaining. So it sounds like the best solution would be to duplicate this functionality into SQL::Abstract::mysql, but that goes back to what @jhthorsen said about whether it's worth the usefulness v.s development+maintenance time.

**Comment by ggl** [comment]
I think it shouldn't require on SQL::Abstract at all. It could take a builder option at or after object creation which could specify which builder one wants to run as a code ref. Then we could use SQL::Abstract or SQL::Maker or something else and not have a hard dependency on SQL::Abstract. Btw, SQL::Maker is also easier to extend via plugins.

**Comment by jhthorsen** [comment]
I'll consider a PR, but closing this issue for now since it is very old.
