### ISSUE TITLE
"Expanding" Date[time] columns into DateTime objects

### ISSUE THREAD

**Issue by ViktorNacht** [jhthorsen/mojo-mysql#65]
Please don't hesitate to just close this, I just wanted to throw it out there that I'm frequently running into the need to convert date[time] columns into DateTime objects. Naturally this can be done with some combination of the Mojo::Collection tools with the object returned by $result->hashes, maybe inside of a model, but it could be very elegant to automagically create DateTime objects or at least pass some column names to instantiate.

DateTime is a core module, so it shouldn't add any dependancies. I feel this this is such a common need it might be worth the effort, but I totally understand if this sounds useless or like future bloat. 

V

**Comment by Grinnz** [comment]
This would only really make sense with a customizable 'expand' functionality which has been attempted in https://github.com/mojolicious/mojo-pg/pull/18 but this implementation was not accepted in Mojo::Pg at the time.

**Comment by Grinnz** [comment]
DateTime is not a core module, by the way.

One implementation on the user end could be:

```
my $strp = DateTime::Format::Strptime->new(pattern => '%F %T', time_zone => 'local');
...
my $rows = $result->hashes->each(sub { $_ = $strp->parse_datetime($_) for @$_{qw(datetime columns)} });
```

You could also use Time::Piece, which is a core module, but which doesn't support any time zones other than UTC and the local time zone of the machine.
```
use Time::Piece;
my $rows = $result->hashes->each(sub { $_ = localtime->strptime($_, '%F %T') for @$_{qw(datetime columns)} });
```

It is also possible, in a roundabout way, that this could be added as a role for Mojo::mysql::Results.

The time zone issue is another challenge to doing this by default. MySQL timestamps come back with no time zone information and are interpreted according to the time_zone variable which defaults to the local time zone of the server (which could easily be different from the local time zone where Mojo::mysql is used), and MySQL datetimes have no time zone information whatsoever (so you essentially have to know what time zone they were created with, or create a 'floating' DateTime object).

**Comment by jhthorsen** [comment]
I’m not going to add this, unless a very generic proposal is made. I think something like adding a date_class attribute to the result class might work, but adding DateTime as a dependency is not going to happen, simply because I’m not a fan. I wonder if an expand hook could work better, so the end user can inflate any data.

What makes this hard for me is that I’m guessing as soon as we add something like this, people will ask for the reverse, when inserting data..?

**Comment by jhthorsen** [comment]
I’m leaving the issue open for discussion though. It’s interesting to see where this goes :)

**Comment by Tekki** [comment]
Not at least we have to think about, or would have to measure, how such an addition affects the speed of `_expand`. With the last changes we already saw that these `grep` operations are time consuming. So it is probably better to solve this on the application level where you already know exactly which columns have to be converted.

**Comment by jhthorsen** [comment]
I'm going to close this, since it seems like the issue has gone stale.
