### ISSUE TITLE
error in installing mojo::mysql

### ISSUE THREAD

**Issue by Shalini-94** [jhthorsen/mojo-mysql#67]
hi,
can anyone suggest how to resolve the issue mojo::mysql error. if i run the mojo script its throwing the error has **"Can't locate Mojo/mysql.pm in @INC (you may need to install the Mojo::mysql module)"*
![mojo_mysql](https://user-images.githubusercontent.com/51451787/60508736-edf34680-9ce8-11e9-9cef-778801fdf0f0.png)
*

**Comment by Tekki** [comment]
The error message says that the installation of DBD::mysql fails. Before I ask you to look into `build.log`: Are the MySQL or MariaDB client libraries installed on your system?

**Comment by jhthorsen** [comment]
@Shalini-94: Please do look at the build error log on the first line that starts with "!".

I'm closing this, because it's not an Mojo::mysql issue. (The screenshot clearly states the same thing)
