### ISSUE TITLE
Remove EXPERIMENTAL from lib/Mojo/mysql.pm

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/mojo-mysql#8]
I think it's time we remove EXPERIMENTAL from this distribution. What do you think?

**Comment by harry-bix** [comment]
I am working on replacing use of DBI and DBD::mysql with pure perl async implementation.
I am not sure if this should be a new version or new module.
I will make a Pull Request soon, let's decide then.

**Comment by jhthorsen** [comment]
I think the API should be the same, but maybe it would be nice if you could choose backend: Either whatever-you're-making or DBD::mysql.

**Comment by harry-bix** [comment]
API is the same (almost).
Incompatible change is $db->dbh and $result->sth are not available.

**Comment by jhthorsen** [comment]
`dbh` should stay, but marked as unavailable (or something) when you use your backend. `sth` can probably be mocked, but adding a compatibility layer.

The reason why I think this is a good idea, is that it should be extremely easy to move from Mojo::Pg to Mojo::mysql, or the other way around.

**Comment by harry-bix** [comment]
I agree, we should be as compatible as possible with Mojo::Pg

**Comment by harry-bix** [comment]
The other backend is called Mojo::mysql::Connection
https://github.com/harry-bix/mojo-mysql/blob/no-dbi/lib/Mojo/mysql/Connection.pm

**Comment by harry-bix** [comment]
#9 is created.  
Still needs more tests and documentation.

**Comment by jhthorsen** [comment]
I'm closing this because of the suggested changes in #9 and #12. (They most certainly make this dist experimental)
