### ISSUE TITLE
cpan archive contains DBD::mysql

### ISSUE THREAD

**Issue by chorny** [jhthorsen/mojo-mysql#82]
including its repository.
See https://metacpan.org/source/JHTHORSEN/Mojo-mysql-1.20/local%2FDBD-mysql

**Comment by Grinnz** [comment]
Since EUMM is the authoring tool here, the MANIFEST.SKIP probably needs to be improved.

**Comment by jhthorsen** [comment]
Thanks for letting me know! 👍 This should be fixed in v1.22. I've also gone to PAUSE and deleted all my older uploads.
