### ISSUE TITLE
Mojo::mysql::Results::_expand() issues warnings on NULL columns.

### ISSUE THREAD

**Issue by augensalat** [jhthorsen/mojo-mysql#83]
For a table that contains columns with `NULL` values a Perl warnings is issued when `$results->expand(!0)`:
```
Use of uninitialized value $_ in pattern match (m//) at /deps/local/lib/perl5/Mojo/mysql/Results.pm line 85.
```

**Comment by jhthorsen** [comment]
The reason this took so long is that the issue had no description on how to reproduce the issue.

This is however fixed now, since I found some spare time to investigate further.
