### ISSUE TITLE
Documentation misleads its readers that "FOR UPDATE SKIP LOCKED" is supported

### ISSUE THREAD

**Issue by akarelas** [jhthorsen/mojo-mysql#85]
In https://metacpan.org/pod/SQL::Abstract::mysql#FOR

...it says:

```
$abstract->select('some_table', '*', undef, {for => \'update skip locked'});
```

However that syntax is not supported, neither in MySQL nor MariaDB.

**Comment by jhthorsen** [comment]
I don’t understand. What’s this then? https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html

**Comment by akarelas** [comment]
Hmm... :-) That's something newer than what I was reading.
Closing.
