### ISSUE TITLE
Remove DBD::mysql as dependency

### ISSUE THREAD

**Issue by saintserge** [jhthorsen/mojo-mysql#88]
Hi,
Is it possible to remove DBD::mysql from dependency? I use only DBD::MariaDB  and obviously it blocks me to install Mojo::mysql as it in requireds list?

Thanks.

**Comment by jhthorsen** [comment]
How does that block you?

**Comment by saintserge** [comment]
Thanks for the reply!
Not allowing my to install through cpanm/cpm as I do not have  DBD::Mysql on my system.

**Comment by jhthorsen** [comment]
I hope this is fixed in the upcoming release.

**Comment by jhthorsen** [comment]
Changed to either look for DBD::MariaDB or the environment variable `MOJO_MYSQL_PREFER_MARIADB=1`.

**Comment by saintserge** [comment]
Hi Jan,
Thanks, but it looks like changes are was not released?

**Comment by jhthorsen** [comment]
That's weird. Anyways, I will make another release soon that supports MOJO_MYSQL_PREFER_DRIVER, but will also use DBD::MariaDB if it's available.

- ef8fc747cb3eeb6f485be9796f7fb6c1dbb40060
- 4991552a5c3c6a121a32cb2112ebdc9c59862e76

**Comment by saintserge** [comment]
Thank you very much!
